project:
  type: website
  preview:
    port: 4200

website:
  page-navigation: true
  title: "Doss-Gollin Lab @ Rice CEVE"
  site-url: https://dossgollin-lab.github.io/
  repo-url: https://www.github.com/dossgollin-lab/dossgollin-lab.github.io
  repo-actions: [issue]
  open-graph: true
  favicon: _assets/img/logos/logo.ico

  search:
    location: navbar
    type: overlay

  page-footer:
    left: |
      View the source [on GitHub]({{< var website.repo-url >}})

  navbar:
    right:
      - text: "People"
        href: people/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Join Us"
        href: joinus.qmd
      - text: "Contact"
        href: contact.qmd
      - text: Links
        menu:  
        - text: "Lab Guide"
          href: https://dossgollin-lab.github.io/lab-guide/
        - text: "AI 4 Climate Risk and Resilience @ Rice"
          href: https://ai4climaterrr.rice.edu
        - icon: github
          text: "GitHub"
          href: https://github.com/dossgollin-lab/


format:
  html:
    #theme: _assets/theme/theme-rice.scss
    #css: styles.css
    theme: [sandstone, _assets/theme/theme-rice.scss]
    toc: false
    anchor-sections: true
    code-overflow: wrap
    citations-hover: true
    code-annotations: hover
    html-math-method: mathjax
    date-format: long

# references
bibliography: _bibliography/my-papers.bib
biblio-style: _assets/references/american-geophysical-union.csl

link-external-newwindow: true
